language: go
go:
  - 1.3
  - 1.2
  - tip
services:
  - redis
install:
  - go get github.com/tools/godep
  - go get golang.org/x/tools/cmd/cover
  - ./build
  - sudo ./install
script:
  - ./test
  - bash integration/redis/test.sh
